/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


using System;
using System.Runtime.InteropServices;

public class libqdftgraph {
  public static SWIGTYPE_p_namespace std {
    set {
      libqdftgraphPINVOKE.std_set(SWIGTYPE_p_namespace.getCPtr(value));
      if (libqdftgraphPINVOKE.SWIGPendingException.Pending) throw libqdftgraphPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      SWIGTYPE_p_namespace ret = new SWIGTYPE_p_namespace(libqdftgraphPINVOKE.std_get(), true);
      if (libqdftgraphPINVOKE.SWIGPendingException.Pending) throw libqdftgraphPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public static SWIGTYPE_p_namespace qdft {
    set {
      libqdftgraphPINVOKE.qdft_set(SWIGTYPE_p_namespace.getCPtr(value));
      if (libqdftgraphPINVOKE.SWIGPendingException.Pending) throw libqdftgraphPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      SWIGTYPE_p_namespace ret = new SWIGTYPE_p_namespace(libqdftgraphPINVOKE.qdft_get(), true);
      if (libqdftgraphPINVOKE.SWIGPendingException.Pending) throw libqdftgraphPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

}
